### PR TITLE
Update to newest TimelineJS release (2.29.1)

### PR DESCRIPTION
**Pull request by titaniumbones**
Very modest changes, there are probably features that the plugin as currently constituted doesn't take advantage of.  I am not noticing any breakage, though.

### CODE REVIEW

**Comment by titaniumbones** [comment]
fixes #7 ?

**Comment by jjeaton** [comment]
Could you squash a9c1ee3, b83736f, 8ef223f and re-push?

There are so many files updated, it's hard for me to tell at a glance, did you just drop in the latest Timeline version, or did you have to make any updates to rest of the plugin (besides the stripslashes change)

**Comment by titaniumbones** [comment]
google says:

---

Note: do not squash commits that you’ve already shared with others. 

## You’re changing history and it will cause trouble for others.

I looked over the commits & all 3 of them are just updates of timelinejs 
-- I just screwed up the first couple times (hadn't read the timelinejs 
docs properly), and had never squashed commits before so didn't know how 
to remove my screwups from the history. I'm reluctant to do it now as I 
don't want to mess anything up in my own tree; if it's a big deal though 
I will give it a try.

m

**Comment by jjeaton** [comment]
@titaniumbones I prefer to have a clean history (OCD) but I can get over that. :) I will merge this once I've had a chance to pull down your branch and test it.

**Pull request merged**
