### PR TITLE
Adds "history" like icon for admin menu page. Adds README.md. Removes readme.txt.

### PR DESCRIPTION
**Pull request by tristanhall**
Removes unused $icon_url & $position variables.

### CODE REVIEW

**Comment by jjeaton** [comment]
@triscuittt I'm good with the icon change and adding the .md README, but could you revert the readme.txt deletion? I wouldn't want to remove it from this repo until I had a script set up to convert it on the fly before pushing to the .org repo.

**Comment by tristanhall** [comment]
@jjeaton Yep, just reverted it.

**Comment by jjeaton** [comment]
thanks!

**Comment by jjeaton** [comment]
Fixes #1

**Pull request merged**
